linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - goerr113
    - prealloc
    - nilerr
    - makezero
    - wastedassign
    - rowserrcheck
    - sqlclosecheck
    - gocyclo
    - funlen

linters-settings:
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '2'
      - '3'
      - '20'
      - '24'
      - '100'
      - '3600'
    ignored-functions:
      - strings.SplitN
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 50
  lll:
    line-length: 140

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - text: 'should not use underscores in package names'
      linters:
        - stylecheck
    - text: "var-naming: don't use an underscore in package name"
      linters:
        - revive
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - lll
        - gofmt
run:
  timeout: 5m